name = "dollar-price-bot"
main = "src/worker.js"
compatibility_date = "2024-05-01"

[vars]
BOT_TOKEN = ""
TARGET_CHANNEL_ID = ""
FETCH_API_URL = ""

[[kv_namespaces]]
binding = "PRICE_KV"
id = ""
preview_id = ""

[triggers]
crons = ["*/10 5-19 * * *", "59 19 * * *"]
